title: "完全に自動でメンテナンスリリースされていくモバイルアプリを作ってみる実験"
summary: |
  iOSとAndroidアプリにおける定期的なメンテナンスリリースを、手動の作業や人による判断プロセスを挟まずに「完全に自動」で行う方法を紹介します。

  内容のレベル感としては、モバイルアプリの開発経験がある方を想定しています。

  実際にこの方法で私が1ヶ月間実験した結果、週に平均5回リリースできるようになりました。
topics: ["ios", "android", "flutter"]
published: false
price: 0
chapters:
  - abstract
  - system-summary
  - setup-for-implementation
  - automated-pr-updating-libraries
  - require-checks-to-merge-pr
  - automated-merge-pr
  - trigger-regular-release
  - check-apps-status
  - check-unreleased-diff
  - e2e-testing
  - update-apps-status
  - deploy-prod
  - update-apps-status-to-released
