name: Contents

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' && (github.event_name == 'pull_request' || github.event_name == 'issue_comment') }}
    runs-on: ubuntu-latest
    name: Run PR agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          github_action_config.auto_review: "true"
